### ISSUE TITLE
Combine audio with video fragments which are being published to kvs using kvssink plugin

### ISSUE THREAD

**Issue by aman-aguptaaa** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#1022]
I am using kvssink plugin to write audio and video to same kvs. And consume audio and video files separately from same kvs via kvs parsing library.
But is there a way to combine the audio and video fragments ? I thought that kvs might maintain audio and video streams as tracks and we can easily read the combined media from kvs. But this is not the case.
Before sending audio and video fragments, muxing does not work (because of difference in pad capabilities of muxer and kvssink plugin). Is there a way to do so before sending audio and video fragments ? The example mentioned [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/687#issuecomment-807859411)  also does not use any mux before sending media.

so, my question is -

- Is there a way to combine audio and video before sending them via kvs plugin?
- Is there a way to combine audio and video fragments after receiving them ? (i can think of timestamp based combination of fragments, but not sure if this is recommended approach)
- What is the recommended way to proceed here ?

**Comment by hassanctech** [comment]
We do not have separate audio and video fragments, a single fragment can contain both audio and video frames.  You do not see the muxing happening explicitly in the GStreamer pipeline because under the hood the Producer SDK muxes them together into separate tracks (so audio and video will be separate tracks).  The SDK packages the incoming data on-the-fly into MKV.

There is no way to consume data only on a single track, when you call GetMedia you will get everything (audio and video).

The summary here is the client application doesn't need to do anything the SDK will take care of this.  If you see evidence of otherwise ,you can cut a new issue and attach media on which the issue is reproducible.
