### ISSUE TITLE
No fragment found

### ISSUE THREAD

**Issue by fabolandry** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#142]
It's seem to be working but I have the error message:
No Fragments found
No video fragments were found. Verify that video is currently being streamed and that the fragment timecodes are correct.

No Live feed is showing from my Rpi-3

Below you can see a screen shoot of what I have on the terminal 
![image](https://user-images.githubusercontent.com/8674637/47269869-7265b680-d518-11e8-9c6c-98c5e6cbc9a0.png)

**Comment by zhiyua-git** [comment]
Hi @fabolandry ,

Can you double check whether you are using the correct region in the console that matches the applications region (the default in the application is us-west-2)?

Also, could you please either paste the logs here or email those to kinesis-video-support@amazon.com which can help to understand the root cause?

Thanks,
-ZH

**Comment by fabolandry** [comment]
I changed the region to us-west-2. It's working. Thank you so much. Great Project !!!!!!!

**Comment by unicornss** [comment]
Glad to hear that @fabolandry.
