### ISSUE TITLE
compiling with plugins

### ISSUE THREAD

**Issue by matti** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#156]
After https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/docker_native_scripts/Dockerfile has compiled, gstreamer is missing plugins like https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-plugin-ximagesrc.html#plugin-ximagesrc

How can I get those included?

**Comment by chehefen** [comment]
The plugin is missing because it's currently disabled when we build the plugin-good: [https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/386526e3a4776a1b4049a80f4d2d4b09081284e2/kinesis-video-native-build/install-script#L538](url)

To enable the plugin, remove `--disable-x` in that line, delete `$DOWNLOADS/local/lib/libgstbadvideo-1.0.so`, then run install-script again.

**Comment by matti** [comment]
I did that and then I get some complication errors - this is just too hard, please allow plugins to be specified.

**Comment by unicornss** [comment]
Hi @matti ,
If additional support is required, please send email to kinesis-video-support@amazon.com with your use case and logs. Thanks

**Comment by matti** [comment]
no worries, this has been made so complicated that I'll never use this piece of shit again.
