### ISSUE TITLE
Ideal setting to get the most FPS?

### ISSUE THREAD

**Issue by davidgatti** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#158]
Hello Streaming Gods :P 

I'm working with your project for a while now, and recently I started using a RPi Zero to stream to KVS and then analyze the video with Rekognition for a demo for a client. All works well despite Rekognition thinking some times that I'm a woman 😅. 

The thing that I can't quite figure out is the FPS count, and what is the best setting to set to get a bigger number. From my experiments it seams that the `key-int-max` plays an important role with this. If I run the following command on average with my upload speed that I get 6 FPS.

```
gst-launch-1.0 v4l2src do-timestamp=TRUE device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=320,height=240,framerate=25/1 ! x264enc bframes=0 key-int-max=3 bitrate=256 ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=my-stream storage-size=128 frame-timestamp=dts-only
```

If I increase this number to 10, i barely get 1FSP, so this is the brake down:

- 1 = 6.36866 FPS
- 2 = 7.15649 FPS
- 3 = 6.65271 FPS
- 4 = 5.13363 FPS

Also the lower the value the more logs you'll spit out, or rather you show more metric results. If we check the GStream docs for the [key-int-max](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-ugly-plugins/html/gst-plugins-ugly-plugins-x264enc.html#GstX264Enc--key-int-max) we get `Maximal distance between two key-frames`, which dose not mean much to me, so my questions are:

- what is this distance?
- how is this distance measured
- how `key-int-max` should be used.
- why you show more metric results with a lower number? Or what triggers a metric output?

**Comment by MushMal** [comment]
@davidgatti thanks!

There are few key parameters you can try to modify. In you example your framerate is set to 25 fps which should be adequate. However, you might want to change the resolution and bitrate parameters to see what's more suitable - in your case it's set to 320x240 and the encoder bitrate is at 256Kbps. Could you please try to increase the resolution and see if it has an effect?

Also, please check the CPU load - if there are other competing applications/processes then it might starve the encoder threads producing lower FPS.

key-int-max is a parameter that controls how many frames will be in between of any key-frames. Generally, we recommend having 2 second GoPs which at 25 fps would evaluate to this value being 50.

The C++ SDK outputs metrics on every key-frame, hence the spew as you have more frequent key-frames. We will fix the SDK to not spew as often.

**Comment by davidgatti** [comment]
I have a follow up question: if the `key-int-max` is bigger that means that there will be way more compression applied to compress the difference between key frames - would this be a true or false statement?

**Comment by MushMal** [comment]
@davidgatti sorry for the delay. First thing... It seems that you are trying to use x264enc encoder which is a software encoder. This is the main reason why you are getting low FPS and your CPU load is very high. We recommend utilizing the omxh264enc which will utilize the GPU for the H264 encoding. Our KVS samples are based on this encoder for RPi. This should produce reasonable FPS.

Now, to answer your questions.. In GStreamer you can set the GoP (Group of Pictures) size by setting the key-int-max parameter. It basically suggests to the encoder to insert an Idr frame every N-th frame. Having larger GoPs up-to 10 seconds will generally decrease the density of the encoded stream. 

You are getting MAX_FRAGMENT_DURATION_REACHED error from the backend as our max fragment duration is set to 10 seconds. Due to the fact that your FPS is so low, the fragmentation exceeds the max duration. Having the hardware encoder will improve the FPS.

Please let us know how it goes.

**Comment by davidgatti** [comment]
Hmm I think I got confused with the readme and multiple option. I copied the CLI from the readme and it works, but you still have a typo in your README despite #129.
