### ISSUE TITLE
No such element or plugin 'kvssink'

### ISSUE THREAD

**Issue by uyennguyen16900** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#506]
After running `make` in the build directory I executed CMake, I followed the instructions to set the environment variables. 
I got `No such element or plugin 'kvssink'` when I ran `gst-inspect-1.0 kvssink`

![Screen Shot 2020-07-08 at 3 11 00 PM](https://user-images.githubusercontent.com/45802706/86999834-77ddb700-c168-11ea-8ed8-f6c72596a195.png)

I don't know if my build failed or GST_PLUGIN_PATH is not set properly. Any help is much appreciated!

**Comment by disa6302** [comment]
@uyennguyen16900 ,

Did you run cmake with `-DBUILD_GSTREAMER_PLUGIN=TRUE` ? 
Can you check if gstkvssink library exists in the build directory?

**Comment by uyennguyen16900** [comment]
I did run `cmake ..  -DBUILD_GSTREAMER_PLUGIN=TRUE `.
I don't see gstkvssink library exists in the build directory.

![Screen Shot 2020-07-08 at 10 42 10 PM](https://user-images.githubusercontent.com/45802706/87001452-541c7000-c16c-11ea-90de-e80faa4acaef.png)

**Comment by chehefen** [comment]
do you have gstreamer in your system?

**Comment by uyennguyen16900** [comment]
I did download gstreamer

**Comment by brahama** [comment]
I am having same issue here. Brew install gstreamer and still can not find.

**Comment by franktseng0718** [comment]
@uyennguyen16900  I met the same problem as you. How did you solve this problem finally?

**Comment by AtiqZaman** [comment]
I am facing the same issue

> After running `make` in the build directory I executed CMake, I followed the instructions to set the environment variables.
> I got `No such element or plugin 'kvssink'` when I ran `gst-inspect-1.0 kvssink`
> 
> ![Screen Shot 2020-07-08 at 3 11 00 PM](https://user-images.githubusercontent.com/45802706/86999834-77ddb700-c168-11ea-8ed8-f6c72596a195.png)
> 
> I don't know if my build failed or GST_PLUGIN_PATH is not set properly. Any help is much appreciated!

I am facing the same issue, can anybody help?

**Comment by MushMal** [comment]
> I am facing the same issue
> 
> > After running `make` in the build directory I executed CMake, I followed the instructions to set the environment variables.
> > I got `No such element or plugin 'kvssink'` when I ran `gst-inspect-1.0 kvssink`
> > ![Screen Shot 2020-07-08 at 3 11 00 PM](https://user-images.githubusercontent.com/45802706/86999834-77ddb700-c168-11ea-8ed8-f6c72596a195.png)
> > I don't know if my build failed or GST_PLUGIN_PATH is not set properly. Any help is much appreciated!
> 
> I am facing the same issue, can anybody help?

You might want to do some debugging yourself. There are plenty of other issues closed in the repository with the same issue. Ensure you specify to build gstreamer in the cmake command, make sure it finishes the build correctly, check to see if you have the ginary, set the plugin path and the ld lib path properly and it should work. If you still have issues, please cut a separate issue with detailed report on the above points.

**Comment by AtiqZaman** [comment]
Thanks @MushMal for your reply and giving me a push to to debug by my own, after debugging, i have solved the issue, now my video from web camera is streaming to kinesis video stream.
Problem was that my GST_PLUGIN_PATH was not set properly, 
Althoght i have set the path through below commands :
export GST_PLUGIN_PATH='pwd'/build
export LD_LIBRARY_PATH='pwd'/open-source/local/lib
But that was not actually set because, after setting the above path when i run the below command 
echo  $GST_PLUGIN_PATH
It shows me another path which was not pointing to the kvssing 
So 
What i did is that i loged in as a super user by running below command 
$ sudo su

and then 

export GST_PLUGIN_PATH='pwd'/build
export LD_LIBRARY_PATH='pwd'/open-source/local/lib

After that when i run this command.   $ gst-inspect-1.0 kvssink
it showed me exactly what it has to..
and finally i run below command and my video streaming was started :

$ gst-launch-1.0 v4l2src do-timestamp=TRUE device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink stream-name=atiqVideoStream storage-size=512 access-key='your access key' secret-key='your secret access key'
+1:

**Comment by Void-Mohit** [comment]
**In my case plugin is builded  in amazon-kinesis-video-streams-producer-sdk-cpp folder so I removed /build in export path and it works

```export GST_PLUGIN_PATH='pwd'
export LD_LIBRARY_PATH='pwd'/open-source/local/lib```**

**Comment by Tseema** [comment]
> Thanks @MushMal for your reply and giving me a push to to debug by my own, after debugging, i have solved the issue, now my video from web camera is streaming to kinesis video stream. Problem was that my GST_PLUGIN_PATH was not set properly, Althoght i have set the path through below commands : export GST_PLUGIN_PATH='pwd'/build export LD_LIBRARY_PATH='pwd'/open-source/local/lib But that was not actually set because, after setting the above path when i run the below command echo $GST_PLUGIN_PATH It shows me another path which was not pointing to the kvssing So What i did is that i loged in as a super user by running below command $ sudo su
> 
> and then
> 
> export GST_PLUGIN_PATH='pwd'/build export LD_LIBRARY_PATH='pwd'/open-source/local/lib
> 
> After that when i run this command. $ gst-inspect-1.0 kvssink it showed me exactly what it has to.. and finally i run below command and my video streaming was started :
> 
> $ gst-launch-1.0 v4l2src do-timestamp=TRUE device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=45 bitrate=500 ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink stream-name=atiqVideoStream storage-size=512 access-key='your access key' secret-key='your secret access key' +1:

this works like a charm. thank you
