### ISSUE TITLE
Trying to stream video on macos docker container using the builtin camera but failed

### ISSUE THREAD

**Issue by YourGraceQI** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#607]
A one liner description about the use case and what you are trying to achieve
I want to video streaming my builtin camera to kvs, and i pull the docker image and run in the docker container,
gst-launch-1.0 v4l2src do-timestamp=TRUE device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc bframes=0 key-int-max=45 bitrate=500 ! video/x-h264,stream-format=avc,alignment=au,profile=baseline ! kvssink stream-name="*" storage-size=512 access-key="*" secret-key="*"
this is my code to launch the stream and it shows error about the device, it seems that inside the container my builtin camera couldn't be reached? I am using MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports), macOS Catalina version10.15.6 
I also run gst-device-monitor-1.0 try to check my device and the error is below:
gst-device-monitor-1.0   
Probing devices...

Failed to start device monitor!

So how could I use the builtin camera inside the docker container and stream it to kvs?
The doc about docker is so limited.

** Any design considerations/constraints **
Explain in detail how you would like to integrate our SDK into your solution 

** If you would not like to open an issue to discuss your solution in open-platform, please email your question to kinesis-video-support@amazon.com **

**Comment by MushMal** [comment]
From what you are describing, the issue is unrelated to KVS at all.

Check out the following link which is the top results when searching in Google.

https://stackoverflow.com/questions/33985648/access-camera-inside-docker-container/33992984

Try to stabilize your media pipeline without KVS using autovideosink and only after that try to stream with KVS sink to eliminate KVS and easily debug the encoder/media source issues first.

Please reactivate if you have any questions related to KVS itself.
