### ISSUE TITLE
[BUG]Segmentation fault when use scp copy it from docker to rock pi

### ISSUE THREAD

**Issue by xiaoyaodingchunqiu** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#895]
it can work in macmini's docker
but after use scp : 
scp -r amazon-kinesis-video-streams-producer-sdk-cpp/ rock@10.10.0.78:/home/rock
When I configure the environment variables and copy the missing files, a segmentation fault is reported
![image](https://user-images.githubusercontent.com/92872460/185894464-63395299-7e16-4cec-b8e3-051842f0c31f.png)
![image](https://user-images.githubusercontent.com/92872460/185894352-348331ca-54f5-40eb-9b57-6c6f321a2e17.png)

what is the right way to deploy kvs to pi?

Thanks

**Comment by disa6302** [comment]
@xiaoyaodingchunqiu , 

Not sure why you require scp, but you can directly build on the Pi. Based on what platform you have built and the toolchains used, you can encounter toolchain related errors when transferred because the expected toolchains do not exist on your device. Please try building the SDK directly on the Pi.
