### ISSUE TITLE
[QUESTION] Running it outside the build folder.

### ISSUE THREAD

**Issue by fX4N1DmH311X39SpxXLWxMWy49n6o8zb** [awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#943]
Hello,
When running the application, I am running into this issue.
```
root@amazon:/# /etc/amazon-kinesis-video-streams-producer-sdk-cpp/build/kvs_gstreamer_sample 
log4cplus:ERROR could not open file ../kvs_log_configuration
log4cplus:ERROR No appenders could be found for logger (com.amazonaws.kinesis.video.gstreamer).
log4cplus:ERROR Please initialize the log4cplus system properly.
```

I have tried the following too.
```
root@amazon:/# /etc/amazon-kinesis-video-streams-producer-sdk-cpp/build/kvs_gstreamer_sample log-config=/etc/amazon-kinesis-video-streams-producer-sdk-cpp/
log4cplus:ERROR could not open file ../kvs_log_configuration
log4cplus:ERROR No appenders could be found for logger (com.amazonaws.kinesis.video.gstreamer).
log4cplus:ERROR Please initialize the log4cplus system properly.
```

```
root@amazon:/# /etc/amazon-kinesis-video-streams-producer-sdk-cpp/build/kvs_gstreamer_sample log-config="/etc/amazon-kinesis-video-streams-producer-sdk-cpp/kvs_log_configuration"
log4cplus:ERROR could not open file ../kvs_log_configuration
log4cplus:ERROR No appenders could be found for logger (com.amazonaws.kinesis.video.gstreamer).
log4cplus:ERROR Please initialize the log4cplus system properly.
```

**Comment by niyatim23** [comment]
Hi @fX4N1DmH311X39SpxXLWxMWy49n6o8zb, it looks like you are not running the application from the build folder. Please cd into the build folder and run the application from there. It should resolve the issue. 

Feel free to open another issue for any other problems / questions

**Comment by disa6302** [comment]
@fX4N1DmH311X39SpxXLWxMWy49n6o8zb ,

Your question is a cmake targetted question. To answer it, you would run cmake. Instead of cmake.. from your root folder. CmakeLists.txt file resides in root, so you need to ensure cmake picks the path. As far as the log config file error, it resides in the root folder as well.  You would have to configure the log path using this property: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/8867047d8d8f56645009ed73788a57f0a6107772/src/gstreamer/gstkvssink.cpp#L547 if you are running gst-launch-1.0.

**Comment by sirknightj** [comment]
Hi @fX4N1DmH311X39SpxXLWxMWy49n6o8zb,
`log-config` is one of the [kvssink GStreamer plugin properties](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-gstreamer-plugin-parameters.html), *not* one of the command-line arguments to the sample.

You can change [this](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/8867047d8d8f56645009ed73788a57f0a6107772/samples/kvs_gstreamer_sample.cpp#L1042) line in the main() method to change the location of the log configuration file:
```
PropertyConfigurator::doConfigure("/home/ubuntu/some/folder/kvs_log_configuration");
```
(make sure to run `make` in the `build` folder to update the binaries after editing!)

I do see that your output says:
```
Error received from element source: Could not open resource for reading.
Debugging information: ../gst/rtsp/gstrtspsrc.c(6427): gst_rtspsrc_setup_auth (): /GstPipeline:rtsp-kinesis-pipeline/GstRTSPSrc:source:
```
Could you confirm that you are able to receive and view the rtsp stream from your rtsp source, and that the uri is inputted correctly? For example, using `vlc`?

**Comment by disa6302** [comment]
@fX4N1DmH311X39SpxXLWxMWy49n6o8zb , 

This would work as well for log configuration.

But your issue is different. I see "Could not open resource for reading.". This indicates permissions issues with accessing the RTSP URL. You would have to debug your source and understand what is going on with it. Closing assuming answered
